export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const ADD_PRODUCT_IMAGE = "ADD_PRODUCT_IMAGE";
export const GET_ALL_DATA = "GET_ALL_DATA";
export const LOADING_PRODUCT_DATA = "LOADING_PRODUCT_DATA";
